### ISSUE TITLE
Temperature deviation query returns error

### ISSUE THREAD

**Issue by jennywlove** [ExtremeEmpress/ouradb#2]
This was working great up until 2 weeks ago but I just tried to run the query again today and am now getting an error.

Here's my query:
```
py oura/oura_query.py --pat=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --start=2022-09-27 --end=2022-10-07|jq '.temperature_deviation'
```

Here's the error:
```
File "C:\users\jenny\ouradb-main\oura\oura_query.py", line 83, in <module>
    main()
  File "C:\users\jenny\ouradb-main\oura\oura_query.py", line 78, in main
    data = fetch_data(tmp_date,end_date,datatype,pat)
  File "C:\users\jenny\ouradb-main\oura\oura_query.py", line 15, in fetch_data
    if not response[datatype]:
KeyError: 'sleep'
```

Appreciate you creating this, it makes tracking temps with the oura ring so much easier!

**Comment by ExtremeEmpress** [comment]
I was faced with this just a few days ago as well. It turns out the old access token had expired. Just create a new access token, and you should be back in action!

I could still update the scripts so that this particular use case would print a more informative error message. So I'll keep this open until then.

And thank you! I am happy to see someone actively using it!

**Comment by ExtremeEmpress** [comment]
I will assume this fixed the issue for you as well, and close the issue. Let me know if you still have issues with it!
